# Generated by Django 5.1.1 on 2024-10-07 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Novice', '뉴비'), ('Rookie', '루키'), ('Professional', '프로페셔널'), ('Elite', '엘리트'), ('Maestro', '마에스트로'), ('Legend', '레전드')], max_length=20)),
                ('color', models.CharField(choices=[('#FF0000', 'Red'), ('#000080', 'Navy'), ('#FB36FF', 'Pink'), ('#9F09AC', 'Purple'), ('#000000', 'Black')], max_length=7)),
                ('whistle', models.IntegerField()),
                ('level_number', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=100)),
                ('game_date', models.DateField()),
                ('game_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('max_participants', models.IntegerField()),
                ('region', models.CharField(choices=[('seoul', '서울'), ('gyeonggi', '경기')], max_length=20)),
                ('gender', models.CharField(choices=[('male', '남자'), ('female', '여자'), ('mixed', '혼성')], max_length=10)),
                ('promotion_match', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('upcoming', '신청하기'), ('finished', '마감'), ('cancelled', '취소하기')], max_length=10)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kick_off.level')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('points', models.IntegerField(default=0)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.URLField(blank=True, max_length=255, null=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kick_off.level')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('points_id', models.AutoField(primary_key=True, serialize=False)),
                ('points_log', models.CharField(choices=[('earned', 'Earned'), ('deducted', 'Deducted')], max_length=10)),
                ('points_amount', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to='kick_off.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], max_length=10)),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer')], max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kick_off.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('notification_type', models.CharField(choices=[('game_notification', 'Game Notification'), ('system_notification', 'System Notification'), ('other', 'Other')], max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kick_off.user')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('mission_id', models.AutoField(primary_key=True, serialize=False)),
                ('mission_content', models.TextField()),
                ('completion_status', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, max_length=255, null=True)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kick_off.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kick_off.user')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(blank=True, to='kick_off.user'),
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('apply_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kick_off.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kick_off.user')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', models.URLField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kick_off.game')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kick_off.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kick_off.user')),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
