# Generated by Django 5.1.1 on 2024-10-15 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick_off', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_name',
            field=models.CharField(default='Unnamed Mission', max_length=100),
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('individual', '개인 미션'), ('team', '팀 미션')], default='individual', max_length=10),
        ),
        migrations.AddField(
            model_name='mission',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 15, 1, 10, 28, 688109, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
