# Generated by Django 5.1.1 on 2024-10-15 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick_off', '0002_mission_mission_name_mission_mission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Red'), ('#000080', 'Navy'), ('#FB36FF', 'Pink'), ('#9F09AC', 'Purple'), ('#000000', 'Black'), ('#D1A722', 'Gold')], max_length=7),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='level',
            name='whistle',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
