# Generated by Django 5.1.1 on 2024-10-15 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick_off', '0003_alter_level_color_alter_level_level_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='social_login_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_login_provider',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='level',
            name='whistle',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
