# Generated by Django 5.1.1 on 2024-10-15 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick_off', '0004_remove_level_description_user_social_login_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kick_off.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kick_off.user')),
            ],
        ),
    ]
