# Generated by Django 5.1.1 on 2024-10-15 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick_off', '0005_usermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='video_url',
        ),
        migrations.AddField(
            model_name='mission',
            name='example_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kick_off.game'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('individual', '개인 미션'), ('team', '팀 미션')], max_length=10),
        ),
    ]
