# Generated by Django 5.1.1 on 2024-10-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick_off', '0007_rename_example_image_mission_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('Novice', '뉴비'), ('Rookie', '루키'), ('Professional', '프로페셜'), ('Elite', '엘리트'), ('Maestro', '마에스트로'), ('Legend', '레전드')], max_length=20),
        ),
    ]
