# Generated by Django 5.1.1 on 2024-10-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick_off', '0009_alter_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
