# Generated by Django 5.1.1 on 2024-10-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kick_off', '0010_mission_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='game',
        ),
    ]
